### ISSUE TITLE
앱이 없잖아

### ISSUE THREAD

**Issue by jing341** [sean0317/app_2020#1]
http://sean0317.github.io/app_2020 로 갔는데 앱이 없어

**Comment by jing341** [comment]
나중에 올릴꺼지?

**Comment by jing341** [comment]
나중에 올릴꺼지?

**Comment by jing341** [comment]
그치?

**Comment by sean0317** [comment]
그거 망함(git init, git push origin master같은거 다 애러남)

2020년 12월 4일 (금) 오후 12:49, jing341 <notifications@github.com>님이 작성:

**Comment by sean0317** [comment]
그거 망함(git init, git push origin master같은거 다 애러남)

**Comment by jing341** [comment]
깃허브 좀 알고 하지...

**Comment by jing341** [comment]
(나는 다 잘댐>자랑질)

**Comment by sean0317** [comment]
zz

2020년 12월 4일 (금) 오후 1:36, jing341 <notifications@github.com>님이 작성:

**Comment by jing341** [comment]
이슈 열었다 닫을 수도 있네

**Comment by jing341** [comment]
계속 에러나면 클론코딩 책 추천함

**Comment by jing341** [comment]
니콜라스 선생님이 가르치는 영상 들어봐

**Comment by sean0317** [comment]
클론코딩 책좀 사서 봐야겠네(참고로 니코쌤 강의를 사서 못봐ㅜㅜ 엄마가 허락 안해줄듯ㅜㅜ)

2020년 12월 6일 (일) 오후 9:28, jing341 <notifications@github.com>님이 작성:
